### PR TITLE
fix such that runs on MacOS

### PR DESCRIPTION
**Pull request by julemai**
had to rename a file that contained a dash and had to include an `__init__.py`

### CODE REVIEW

**Comment by lintool** [comment]
@gauchm can you take this review?

**Review by gauchm — APPROVED** [review]
lgtm

**Comment by julemai** [comment]
Means I can merge, right?

**Comment by gauchm** [comment]
Yes! (lgtm = Looks good to me)

**Comment by julemai** [comment]
I indeed had to google that. Hahaha!

**Pull request merged**
